export const DISCUSSION_GET_REQUEST = "DISCUSSION_GET_REQUEST";
export const DISCUSSION_GET_SUCCESS = "DISCUSSION_GET_SUCCESS";
export const DISCUSSION_GET_FAIL = "DISCUSSION_GET_FAIL";

export const DISCUSSION_GET_BY_ID_REQUEST = "DISCUSSION_GET_BY_ID_REQUEST";
export const DISCUSSION_GET_BY_ID_SUCCESS = "DISCUSSION_GET_BY_ID_SUCCESS";
export const DISCUSSION_GET_BY_ID_FAIL = "DISCUSSION_GET_BY_ID_FAIL";
