export const DISCUSSION_GET_REQUEST = "DISCUSSION_GET_REQUEST";
export const DISCUSSION_GET_SUCCESS = "DISCUSSION_GET_SUCCESS";
export const DISCUSSION_GET_FAIL = "DISCUSSION_GET_FAIL";

export const DISCUSSION_GET_BY_ID_REQUEST = "DISCUSSION_GET_BY_ID_REQUEST";
export const DISCUSSION_GET_BY_ID_SUCCESS = "DISCUSSION_GET_BY_ID_SUCCESS";
export const DISCUSSION_GET_BY_ID_FAIL = "DISCUSSION_GET_BY_ID_FAIL";

export const SET_CATEGORY_REQUEST = "SET_CATEGORY_REQUEST";
export const SET_CATEGORY_SUCCESS = "SET_CATEGORY_SUCCESS";
export const SET_CATEGORY_FAIL = "SET_CATEGORY_FAIL";
