export const DISCUSSION_GET_REQUEST = "DISCUSSION_GET_REQUEST";
export const DISCUSSION_GET_SUCCESS = "DISCUSSION_GET_SUCCESS";
export const DISCUSSION_GET_FAIL = "DISCUSSION_GET_FAIL";

export const DISCUSSION_GET_BY_ID_REQUEST = "DISCUSSION_GET_BY_ID_REQUEST";
export const DISCUSSION_GET_BY_ID_SUCCESS = "DISCUSSION_GET_BY_ID_SUCCESS";
export const DISCUSSION_GET_BY_ID_FAIL = "DISCUSSION_GET_BY_ID_FAIL";

export const DISCUSSION_GET_BY_CATEGORY_REQUEST =
  "DISCUSSION_GET_BY_CATEGORY_REQUEST";
export const DISCUSSION_GET_BY_CATEGORY_SUCCESS =
  "DISCUSSION_GET_BY_CATEGORY_SUCCESS";
export const DISCUSSION_GET_BY_CATEGORY_FAIL =
  "DISCUSSION_GET_BY_CATEGORY_FAIL";

export const DISCUSSION_LIKE_REQUEST = "DISCUSSION_LIKE_REQUEST";
export const DISCUSSION_LIKE_SUCCESS = "DISCUSSION_LIKE_SUCCESS";
export const DISCUSSION_LIKE_FAIL = "DISCUSSION_LIKE_FAIL";

export const DISCUSSION_DISLIKE_REQUEST = "DISCUSSION_DISLIKE_REQUEST";
export const DISCUSSION_DISLIKE_SUCCESS = "DISCUSSION_DISLIKE_SUCCESS";
export const DISCUSSION_DISLIKE_FAIL = "DISCUSSION_DISLIKE_FAIL";
