export const PROFILE_GET_REQUEST = "PROFILE_GET_REQUEST";
export const PROFILE_GET_SUCCESS = "PROFILE_GET_SUCCESS";
export const PROFILE_GET_FAIL = "PROFILE_GET_FAIL";

export const PROFILE_GET_BY_ID_REQUEST = "PROFILE_GET_BY_ID_REQUEST";
export const PROFILE_GET_BY_ID_SUCCESS = "PROFILE_GET_BY_ID_SUCCESS";
export const PROFILE_GET_BY_ID_FAIL = "PROFILE_GET_BY_ID_FAIL";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";
export const UPDATE_PROFILE_CLEAR = "UPDATE_PROFILE_CLEAR";
